- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - icon
    - temperature
    - hourly_summary
    - minutely_summary
    - apparent_temperature
    - apparent_temperature_low
    - apparent_temperature_high
    - humidity
    - precip_probability
    - precip_intensity
    - wind_speed
    - pressure
    - wind_bearing
    - cloud_cover
  units: si
  language: en
