- platform: template
  sensors:
    local_time:
      value_template: "{{as_timestamp(now()) | timestamp_custom('%-H:%M')}}"
    local_date:
      value_template: "{{as_timestamp(now()) | timestamp_custom('%A %B %-d')}}"
    weather_overnight_low:
      value_template: "{{ states.sensor.dark_sky_overnight_low_apparent_temperature.state|round }}"
    weather_daytime_high:
      value_template: "{{ states.sensor.dark_sky_daytime_high_apparent_temperature.state|round }}"
    weather_current_temp:
      value_template: "{{ states.sensor.dark_sky_apparent_temperature.state|round }}"
    #energy_fibaro_plug:
    #  friendly_name: 'Wall Plug W'
    #  unit_of_measurement: 'W'
    #  value_template: '{{ states.light_wallplug1_5.attributes.current_power_w }}'

